sudo: required
services:
  - docker

before_install:
        - docker build -t swamisub/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t swamisub/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1b"
  app: "docker-react"
  env: "Docker-React-env"
  bucket_name: "elasticbeanstalk-ap-south-1-515260481255"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

