sudo: required
services:
  - docker
#s3://elasticbeanstalk-us-east-1-138402561056/.elasticbeanstalk
# Sabirami-env.dimdidv2px.us-east-1.elasticbeanstalk.com 
before_install:
        - docker build -t swamisub/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t swamisub/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sabirami"
  env: "Sabirami-env"
  bucket_name: "elasticbeanstalk-us-east-1-138402561056"
  bucket_path: "resources"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

