sudo: required
services:
  - docker

before_install:
        - docker build -t swamisub/chooth-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t swamisub/chooth-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-React-env"
  bucket_name: "elasticbeanstalk-ap-south-1-515260481255"
  bucket_path: "docker-react"
  on:
    branch: master
